
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='logux_django',
    version='2.0',
    description='Django Logux integration engine https://logux.org/',
    python_requires='<4,==3.*,>=3.7.0',
    project_urls={"homepage": "https://github.com/logux/django/"},
    author='Vadim Iskuchekov',
    author_email='egregors@pm.me',
    license='MIT',
    classifiers=['Development Status :: 4 - Beta', 'Environment :: Web Environment', 'Intended Audience :: Developers', 'License :: OSI Approved :: MIT License', 'Operating System :: OS Independent', 'Programming Language :: Python', 'Programming Language :: Python :: 3.7'],
    packages=['logux'],
    package_dir={"": "."},
    package_data={},
    install_requires=['django<4,>=2.2', 'requests<3,>=2.22.0', 'semantic-version==2.*,>=2.8.5'],
    extras_require={"dev": ["black==20.*,>=20.8.0.b1", "coverage==5.*,>=5.3.1", "dephell==0.*,>=0.8.3", "django-stubs==1.*,>=1.7.0", "flake8==3.*,>=3.8.4", "mccabe==0.*,>=0.6.1", "pylint==2.*,>=2.6.0", "sphinx==3.*,>=3.4.0"]},
)
