#
# List of test requests from the Logux Proxy server to the Django backend.
# Most of them taked from doc's: https://logux.io/protocols/backend/examples/
#
# All of them are for the version 2

# ###
# Proxy Server auth: https://logux.io/protocols/backend/spec/#requests
#

# Proxy Server auth with correct secret.
POST http://localhost:8000/logux/
Content-Type: application/json

{
  "version": 2,
  "password": "secret",
  "commands": []
}

###

# Proxy Server auth with wrong secret.
POST http://localhost:8000/logux/
Content-Type: application/json

{
  "version": 2,
  "password": "wrong secret",
  "commands": []
}

###

# ###
# Wrong command. Not Auth and not Action
#

# bad command type -> error (tests/test_project/settings.py:122)
POST http://localhost:8000/logux/
Content-Type: application/json

{
  "version": 2,
  "password": "secret",
  "commands": [
    [
      "sup guys!",
      "foo",
      "bar",
      "gf4Ygi6grYZYDH5Z2BsoR"
    ]
  ]
}

###

# ###
# "Auth" command: https://logux.io/protocols/backend/spec/#requests
#

# "auth" command -> authenticated (tests/test_project/settings.py:122)
POST http://localhost:8000/logux/
Content-Type: application/json

{
  "version": 2,
  "password": "secret",
  "commands": [
    [
      "auth",
      "38",
      "good-token",
      "gf4Ygi6grYZYDH5Z2BsoR"
    ]
  ]
}

###

# "auth" command -> denied (tests/test_project/settings.py:122)
POST http://localhost:8000/logux/
Content-Type: application/json

{
  "version": 2,
  "password": "secret",
  "commands": [
    [
      "auth",
      "38",
      "bad-token",
      "gf4Ygi6grYZYDH5Z2BsoR"
    ]
  ]
}

###

# ###
# "Action" command: https://logux.io/protocols/backend/spec/#requests
#

# "action" command -> authenticated (tests/test_project/settings.py:122)
POST http://localhost:8000/logux/
Content-Type: application/json

{
  "version": 2,
  "password": "secret",
  "commands": [
    [
      "action",
      {
        "type": "user/rename",
        "user": 38,
        "name": "New"
      },
      {
        "id": "1560954012838 38:Y7bysd:O0ETfc 0",
        "time": 1560954012838
      }
    ],
    [
      "action",
      {
        "type": "user/rename",
        "user": 21,
        "name": "New"
      },
      {
        "id": "1560954012900 38:Y7bysd:O0ETfc 1",
        "time": 1560954012900
      }
    ]
  ]
}

###

# "action" command -> unknownAction
POST http://localhost:8000/logux/
Content-Type: application/json

{
  "version": 2,
  "password": "secret",
  "commands": [
    [
      "action",
      {
        "type": "user/unknown",
        "user": 38,
        "name": "New"
      },
      {
        "id": "1560954012838 38:Y7bysd:O0ETfc 0",
        "time": 1560954012838
      }
    ]
  ]
}

###