# Generated by Django 2.2.12 on 2020-04-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('age', models.IntegerField(verbose_name='age')),
            ],
            options={
                'verbose_name': 'cat',
                'verbose_name_plural': 'cats',
            },
        ),
    ]
